const testData = '4-7 z: zzzfzlzzz\n' +
    '3-4 l: blllk\n' +
    '8-11 j: jjjjjjjgjjjj\n' +
    '6-7 l: lllhlbl\n' +
    '10-13 x: xmhfsbjxptxxv\n' +
    '2-3 s: ssvxszrvj\n' +
    '4-6 r: rtrrrqv\n' +
    '5-6 c: cbccxc\n' +
    '3-4 g: zwvg\n' +
    '2-4 d: fqfqlcdzbtmph\n' +
    '10-13 s: cmssgslvrssfsl\n' +
    '1-4 d: hdsdddq\n' +
    '2-5 d: jdptwdv\n' +
    '3-4 l: vlcl\n' +
    '2-5 k: mdkkkmkq\n' +
    '3-4 j: wjjt\n' +
    '4-10 h: wmfqghskgjtt\n' +
    '8-9 c: cccccccnp\n' +
    '4-5 q: qqjzm\n' +
    '5-16 h: hhhhhhhhhhhhhhhhhhh\n' +
    '11-14 g: vghggggggggggwggggbg\n' +
    '1-13 s: ssssssssssdsxss\n' +
    '3-6 x: bxlxxznq\n' +
    '16-17 f: hfwfqffffwsffsffl\n' +
    '12-14 v: rbvvgvvwvvvvcvjv\n' +
    '6-8 r: rrfrrrrr\n' +
    '4-13 j: wsbmtjhjtpmljjfbk\n' +
    '2-7 k: pzdwgnknf\n' +
    '14-18 f: tsdqbvgbxwvfhfffpn\n' +
    '4-13 c: vxpccvfhcnvscrtngc\n' +
    '1-2 z: nmbzcz\n' +
    '4-6 k: wkvfcgpsnk\n' +
    '1-4 m: smppnnmm\n' +
    '1-3 v: jlcvv\n' +
    '6-10 f: ffjfsnfbfxfvklfffff\n' +
    '4-7 v: vvvvvvvvv\n' +
    '8-10 c: tcccccdcwcc\n' +
    '4-11 r: xwxfvzbcrvr\n' +
    '2-18 w: rwznqcwkzpqlmngpjnrn\n' +
    '3-19 h: qbhsthtkmhfnnkxvbphk\n' +
    '1-3 b: bbbbb\n' +
    '3-9 p: pppppppppp\n' +
    '10-13 t: tttttttrttttttt\n' +
    '2-3 f: hffjff\n' +
    '1-2 k: zzkkv\n' +
    '4-5 s: snbss\n' +
    '8-11 f: fffffffpfff\n' +
    '8-16 r: hlgcwsqqrpcflnsng\n' +
    '2-8 k: kkkkkkkffvkk\n' +
    '7-15 k: ckcphgbjkpvkrwk\n' +
    '15-17 w: wvlwwnwzwwwwmswwww\n' +
    '1-2 j: zgjjj\n' +
    '5-8 x: xxxxdxxjxxx\n' +
    '12-16 v: qvdnvqdsgcxwqsnv\n' +
    '12-14 s: jswppnmlxbzjwn\n' +
    '1-3 g: ghgg\n' +
    '5-14 k: rbckkkvdltkmckp\n' +
    '9-11 h: qhffhhhdchshh\n' +
    '4-5 g: gggvgg\n' +
    '2-5 t: gtdjfp\n' +
    '7-8 g: vgtdgggb\n' +
    '1-4 s: hbssskscq\n' +
    '12-13 r: rfjrrjrrrrrgg\n' +
    '13-16 j: jjjjjjjjjjjjjjjjjj\n' +
    '3-14 p: hvkjnlhpngzrvpw\n' +
    '8-10 g: kgggwrggggg\n' +
    '12-18 f: fmlbmsfxsgpjnvfkkf\n' +
    '2-3 f: dffg\n' +
    '6-7 l: llllllll\n' +
    '1-3 s: jshth\n' +
    '1-5 s: gssss\n' +
    '3-4 p: mgpptdwztpkfjmgmsw\n' +
    '4-6 c: cfcksc\n' +
    '4-6 v: hvdvgscqv\n' +
    '18-20 t: thtjtvjttbttxtthttpt\n' +
    '2-4 c: cmcc\n' +
    '3-5 q: qqnqhv\n' +
    '6-10 l: pllrllllllxlllh\n' +
    '3-5 k: hzknk\n' +
    '13-17 t: hcttttvdttttjtttpntt\n' +
    '9-14 d: dxdddddddsdddhddddd\n' +
    '4-5 p: rmcps\n' +
    '3-9 z: hzcmfzspk\n' +
    '3-8 v: cmqvvkwv\n' +
    '18-19 n: nnslnnnnnmnnnnnnnxnn\n' +
    '4-5 c: cghcccscccc\n' +
    '11-16 k: kkkkkkmkkkklkkkk\n' +
    '2-5 r: grlrr\n' +
    '6-19 w: wzxxrbwwzjwftpzwzdg\n' +
    '15-16 w: wwwwlwwwwwwwwwjw\n' +
    '3-9 x: pvxtkcnsnrcx\n' +
    '1-8 q: jqmxxgqq\n' +
    '7-9 t: wntmvtnlqt\n' +
    '10-12 t: ttttttzttttt\n' +
    '15-16 c: gjcgjxbnscbcchqc\n' +
    '8-11 g: dgfggjjzggg\n' +
    '10-11 x: brpxrlbkvxf\n' +
    '11-14 p: ppppppppppgpppp\n' +
    '4-13 p: kdmndpfnjpsdp\n' +
    '6-10 j: mmnzjjjhrdj\n' +
    '4-12 b: bbbbhbbhblbsb\n' +
    '10-11 z: zzwrzzzzzhnzz\n' +
    '6-7 s: ssltvnszhr\n' +
    '4-7 k: skckkkkl\n' +
    '1-12 s: sljgsxwslfcqss\n' +
    '12-14 f: wffzfkkfczqtdf\n' +
    '3-4 d: wgqs\n' +
    '6-7 v: vlvvvvqvvpv\n' +
    '2-9 t: kwxfnqpvtsnhm\n' +
    '7-12 b: bbbbbbwbbbbbbbb\n' +
    '2-7 m: rscmzmms\n' +
    '1-5 s: hgjsszkss\n' +
    '8-11 x: vxxrxwxdxxvxrqkrz\n' +
    '8-11 f: fkfdgnqfllfjlc\n' +
    '1-2 g: ngggzggmgjggmtzdgcv\n' +
    '6-11 q: tvjdmvttzvbxfdqgd\n' +
    '5-8 f: fmfffkff\n' +
    '2-5 d: dxddjqdxv\n' +
    '2-8 k: bbpsjxtkljbk\n' +
    '12-16 q: ldqqqqqqqqqqqqqq\n' +
    '2-4 n: nvxf\n' +
    '2-6 w: wwwwwzwv\n' +
    '4-7 h: hhnshhrhh\n' +
    '3-7 g: mgcqcfl\n' +
    '2-4 c: hcbczxmk\n' +
    '15-17 g: ggggggggggggggggfg\n' +
    '12-13 w: wwwwwwwwwwjwww\n' +
    '6-8 r: rgrrrprtr\n' +
    '13-16 n: nqnnnnnnnnnnrnnh\n' +
    '4-7 d: mdddvdd\n' +
    '10-14 p: hpjpwppppsbpwspppp\n' +
    '11-14 v: vvvvvvvvvvvpvfvv\n' +
    '4-5 x: vwxrlxfxbxpq\n' +
    '1-6 v: zvvvvrvv\n' +
    '4-5 q: qqjqqsd\n' +
    '3-4 f: ffff\n' +
    '13-14 m: mmmmmmmdmmmmzz\n' +
    '11-14 r: rrrrzrrtmrqrrrdrl\n' +
    '14-18 q: qqqqqqqqqqqqkgqqqv\n' +
    '2-5 f: mffzfzjmlmrzqk\n' +
    '13-14 x: xxxxxxxtxxxjxxx\n' +
    '1-3 s: qshtqssxsqb\n' +
    '4-11 t: tttptttwttbtt\n' +
    '3-6 s: gbmgst\n' +
    '2-12 v: hvmnqtnvmjdkghcfjmtd\n' +
    '12-19 g: gggggggggggmgggggggg\n' +
    '9-10 m: mmmmmmmmcmm\n' +
    '1-10 f: fffffffffhf\n' +
    '1-12 k: vkkkkkzkkkksk\n' +
    '1-9 m: mmmmmmmmmmmm\n' +
    '4-6 w: wlqwzw\n' +
    '17-18 d: ddddffdddddddddlddd\n' +
    '3-4 g: hgzg\n' +
    '3-5 r: fbrnbr\n' +
    '2-7 j: rrjjsmjjjzj\n' +
    '15-18 n: nnnnnhnnnnnnnnbnnjnn\n' +
    '2-4 b: hzltnwvbs\n' +
    '11-12 k: skkkkkkkkkkk\n' +
    '6-11 x: xxxbxxxxxpjhxvxxxfxx\n' +
    '4-5 d: dhjdd\n' +
    '2-7 v: vbvvbvvvvvvv\n' +
    '4-5 g: ngggl\n' +
    '10-17 p: ppppppptpppppgpppp\n' +
    '5-11 f: fqcfvtpfqhc\n' +
    '7-14 d: hpdsddwtcddqhblt\n' +
    '5-6 k: kkkkqhkkk\n' +
    '4-7 w: vjkwjmwwwwhrv\n' +
    '2-3 c: dcqw\n' +
    '3-4 q: qqnmqqqqqn\n' +
    '3-5 b: bbbbb\n' +
    '13-14 z: qsbkzgzhmzthzzcrp\n' +
    '6-13 t: nttstttttttttttt\n' +
    '13-14 v: xvxvvfjvvvvtvk\n' +
    '2-3 q: qvwqq\n' +
    '1-4 v: nvpsv\n' +
    '3-5 v: vvvvsvvb\n' +
    '3-4 p: npph\n' +
    '1-3 l: lllllf\n' +
    '18-19 j: jjjjjjjjjjjjjjjjjhh\n' +
    '8-12 d: vmhvddqddhdd\n' +
    '2-7 l: rfdzrldw\n' +
    '3-4 n: lnnjsn\n' +
    '2-3 m: mxlfvqmm\n' +
    '16-20 n: nmsnmdhwvwzlsrpnvcdn\n' +
    '8-13 l: lllllllqllllbl\n' +
    '6-7 w: lpwwwvhww\n' +
    '3-5 s: sqsshnwp\n' +
    '1-4 z: zzzk\n' +
    '11-13 z: zzzzzzzzzzjzzzz\n' +
    '2-3 n: nnnnt\n' +
    '2-5 b: jbpdn\n' +
    '2-16 m: bmflbclkmlfkpwdmf\n' +
    '3-4 b: bbjc\n' +
    '10-11 b: bbbdbbbbbbvbbb\n' +
    '5-11 z: zzzzzkzzzzzzzzzzwzzz\n' +
    '2-13 k: qkfbfkxxpvwpqbg\n' +
    '5-8 n: jnxpnngs\n' +
    '2-4 z: bbnk\n' +
    '1-2 w: glww\n' +
    '1-6 g: zggggg\n' +
    '1-3 g: bgjg\n' +
    '8-15 v: vvvvvvvpvvvvvvvvv\n' +
    '2-8 t: jtvkktkg\n' +
    '1-5 n: xzvnp\n' +
    '16-20 w: mnxtkjwkmbqjwnndwwws\n' +
    '7-8 g: xgggggggg\n' +
    '13-15 m: gwjdqbtmnfjfwsmj\n' +
    '1-3 r: lrzrmqrr\n' +
    '14-15 x: xxxxxxxxxxxxxcxx\n' +
    '16-19 c: cccccccccccccccccczc\n' +
    '1-7 j: tbjrsjjnj\n' +
    '11-17 j: jjjjjjjjjjjjjjjjfjj\n' +
    '2-3 s: prsc\n' +
    '5-15 f: qfgftfffffrfffvff\n' +
    '7-11 f: fffffffffffff\n' +
    '9-11 j: vhpjgjfjjkjmvfjvhdj\n' +
    '3-6 g: gggtgggrg\n' +
    '7-9 g: lzgggggfg\n' +
    '6-7 b: bbqtbtb\n' +
    '5-7 h: hfthhfhhhh\n' +
    '12-19 g: lggggggggggnbbggfgl\n' +
    '1-11 z: zzzzzzzzkzzzzz\n' +
    '5-10 r: gxdbrvrzrb\n' +
    '3-4 c: chnc\n' +
    '5-10 h: hhhhhhhhhhhrhhsh\n' +
    '4-5 d: dqrmdd\n' +
    '9-10 z: ztxnxptzzz\n' +
    '3-4 k: kvxksw\n' +
    '3-5 t: gstxtvbsbmzflfrft\n' +
    '1-14 v: vtvdnmqqfjkwft\n' +
    '7-9 n: kgsndnnnn\n' +
    '3-4 p: pvcp\n' +
    '12-14 c: zchftgbmccpcvjbr\n' +
    '1-10 k: cckkkkskjk\n' +
    '1-2 t: tlbt\n' +
    '6-15 j: vqnjjjzjsmctzqj\n' +
    '7-8 n: nnnnnnmxz\n' +
    '10-13 b: bbbbbbhbbcbbb\n' +
    '5-7 m: qmmmmjv\n' +
    '2-8 n: nnncnnntnnnmnnn\n' +
    '3-6 f: mvhwpdnfccnkhxq\n' +
    '5-11 h: hhhhhhhhhhsh\n' +
    '15-16 g: gggdggsgkgggggzg\n' +
    '5-6 j: jjjjjbj\n' +
    '3-4 f: mftk\n' +
    '10-11 p: pxpppppppbppppppp\n' +
    '8-9 g: dnjkxldnwgcdmqgnq\n' +
    '18-20 q: qqqqqqqqqqqqqqqqqqqp\n' +
    '5-7 q: vqpqfqrhqbdkkq\n' +
    '3-5 h: nvhshgvzr\n' +
    '13-14 l: rllnczlblllcll\n' +
    '1-6 r: rnltrrr\n' +
    '17-18 f: fffffffffffffffffff\n' +
    '17-18 z: kzzzfzwzzdklxzskjl\n' +
    '3-9 v: vczjvwrxvmsn\n' +
    '8-13 f: fffffvffffffffffffff\n' +
    '4-8 v: vvznvvvgvv\n' +
    '10-12 l: lmllzlrllblwh\n' +
    '8-11 d: pdcddddcdddbdbdd\n' +
    '1-2 t: dtttttttdzbttckrtt\n' +
    '1-7 w: wwwwwwpzwwww\n' +
    '6-7 d: wsdvprj\n' +
    '17-18 w: tjflkmhjvgfwccdbgw\n' +
    '7-12 p: gfjwrhsmpcvppw\n' +
    '2-3 p: pbpl\n' +
    '18-19 m: mmmmmmmmmmmmmmmmmmmm\n' +
    '3-4 d: bjdbdvjmtp\n' +
    '3-4 l: jlllhblkr\n' +
    '6-7 j: ljbkvlvjnv\n' +
    '5-9 d: dddkddddddd\n' +
    '4-10 l: fxflvrnjxb\n' +
    '2-8 v: bshlrvvvvfk\n' +
    '10-14 p: pppcppppppppprpppp\n' +
    '3-8 w: svwfghvp\n' +
    '2-10 t: tpttttttttt\n' +
    '4-5 s: ssszsssl\n' +
    '1-4 n: nnfn\n' +
    '4-7 w: wwwfwwlwwwwwwwww\n' +
    '11-12 f: tqflrfffqfffffffxc\n' +
    '1-3 q: qfqxbqqbqtcvfkbfng\n' +
    '2-3 n: twnffvn\n' +
    '3-4 x: hxhxwxxxxbxwdt\n' +
    '4-8 k: wnhtrzjwrkcmblnbhc\n' +
    '9-10 m: mmmplzmcmm\n' +
    '14-16 g: cgdgfgvgbfzggcrskll\n' +
    '3-4 f: fhff\n' +
    '6-18 w: wwpskqxwgwwwwcwvxw\n' +
    '6-8 h: fvhqxkwqlssjhmqsv\n' +
    '4-5 k: kkkkk\n' +
    '1-4 n: nnnfn\n' +
    '3-5 r: rrdrrrr\n' +
    '10-11 k: qkkxkkkkkqk\n' +
    '12-13 m: mtmmmmmmmmmhm\n' +
    '3-5 v: kvvhkksv\n' +
    '2-3 m: mrmm\n' +
    '14-17 x: xxxxxxxxxxxxxxxxr\n' +
    '7-8 c: cckccmscmc\n' +
    '9-17 w: wlwwwgwkjzwxmjwhs\n' +
    '1-4 k: kkkkkkkkkk\n' +
    '6-11 j: jjjjzjjjjfj\n' +
    '4-5 s: zssbs\n' +
    '4-6 g: qfrggpcgqwgg\n' +
    '10-13 g: tggggxsgggggggggg\n' +
    '3-9 m: qmzjjjmqnlhc\n' +
    '7-15 p: qlrpprvmgzlltpm\n' +
    '3-6 z: pxzzbzzb\n' +
    '4-12 c: jlkckndszjgcvjfcxw\n' +
    '8-9 r: rrrcrrrrrr\n' +
    '2-12 m: rnmmmlxmvvmzrqmmqw\n' +
    '6-8 t: xpdtttttccz\n' +
    '8-15 p: ppppppppppppppnppk\n' +
    '3-4 j: zzxc\n' +
    '1-8 z: nfqznthhzzgzwsttfbz\n' +
    '3-4 z: znzs\n' +
    '6-9 z: fzzzzzzzszzzzzz\n' +
    '1-2 n: nnnn\n' +
    '3-17 x: hhxhqhfkzvpxlsrzx\n' +
    '4-6 h: thhpkhxhlzdhhrh\n' +
    '11-12 p: ppppppppppfwpppppp\n' +
    '8-11 h: hmgkhhhhhwhhhmhk\n' +
    '3-4 w: wwwwvf\n' +
    '1-5 j: jqjqj\n' +
    '3-11 w: nblvwbwjwmwswfwtsrw\n' +
    '5-10 v: hvrvvggjfv\n' +
    '4-5 j: cjqqs\n' +
    '3-7 n: lnnqnwnnnn\n' +
    '2-4 t: kkmp\n' +
    '13-14 f: ffffffffffffff\n' +
    '6-10 h: tzswmhnbdqqpcv\n' +
    '1-5 v: zvvvvv\n' +
    '8-9 r: rvprrrrrdrr\n' +
    '2-4 l: dwxf\n' +
    '5-7 n: nnnnnjn\n' +
    '9-12 x: xxxxxxxkpxxfxxxxfxx\n' +
    '8-14 x: xxgjxdsccwtfvxq\n' +
    '16-19 h: cbhkhjhmcdxhndnhhnmh\n' +
    '4-8 d: dpdclrdjqd\n' +
    '7-9 t: rtntcctgtrfpmq\n' +
    '3-4 s: smlf\n' +
    '6-7 n: gnljnnnnn\n' +
    '16-18 t: ttttttttttttkttwtdtt\n' +
    '3-5 d: zddzdkws\n' +
    '9-10 w: wwwwwwwwsr\n' +
    '9-11 g: ggggggggggg\n' +
    '11-13 h: jqjhnrrhzxtmhhhhbcq\n' +
    '4-6 x: xxxxxqxxxx\n' +
    '13-18 s: pswsfxfjkhvsskssbsgr\n' +
    '2-6 f: fffffp\n' +
    '14-15 r: rrrrlrrrrsrvrrrrmlrr\n' +
    '9-12 m: smmmzmmtsmnp\n' +
    '9-14 q: xqgqqxqjqgzqlqwnq\n' +
    '2-15 w: wwmwwwwwrwwwwwd\n' +
    '2-6 c: cbcccnc\n' +
    '18-19 r: rrrrrjrrrrrrrrrrrgrk\n' +
    '3-13 d: rvwpflbrfrgpd\n' +
    '5-7 t: ntxttrtprgtvxt\n' +
    '2-14 k: rbffdmghvzwbml\n' +
    '4-5 m: mmhmwc\n' +
    '6-7 z: zkhlqqgpvllmbf\n' +
    '7-10 r: rrrrrrbrpvrr\n' +
    '14-17 m: mmnmmmmmmmmmmbmmmm\n' +
    '3-5 r: rvcrssrrwrr\n' +
    '12-19 t: ttttttttmttbttttttxt\n' +
    '9-19 v: vvvvvvvvpvvvvvvvvvxv\n' +
    '15-18 d: ddhddcddsddddwdldd\n' +
    '7-10 k: qkcmkgkblkxkzb\n' +
    '11-14 n: nnnnnnnnnhnnnnnnn\n' +
    '10-16 k: kkkvkkkkkkktkkkkk\n' +
    '6-8 s: sdfjbrswbwkvsqlz\n' +
    '1-2 g: dsgg\n' +
    '16-19 g: bpggwcpzdgpnggggkrg\n' +
    '5-7 l: rllwlls\n' +
    '8-9 s: sssssssss\n' +
    '12-13 b: bbbbbqbtbbbkb\n' +
    '13-15 w: zwwwwwwtxwwdkvwwww\n' +
    '4-5 c: pccckcc\n' +
    '4-6 v: hnvbrb\n' +
    '3-6 q: jbqrqq\n' +
    '3-4 w: wwwww\n' +
    '5-14 k: hgmkkwxknkwhlkddg\n' +
    '3-4 k: kkdk\n' +
    '4-5 p: ppzppppp\n' +
    '5-7 k: kkkkkkpkk\n' +
    '12-13 m: mmmmmmmmmmmmmmmm\n' +
    '1-6 r: srrrwnsrrrrr\n' +
    '18-20 p: ppppgppffppwpppppppp\n' +
    '7-8 f: ffffffjhffffffff\n' +
    '2-4 l: dsqq\n' +
    '10-12 q: qqqqqqqvqqsf\n' +
    '3-8 l: svrqdrlx\n' +
    '3-5 w: wwswmw\n' +
    '12-15 q: tntnjzqhcnqqqqt\n' +
    '1-8 j: nscgpjmj\n' +
    '7-11 j: jjjtsrjjtjx\n' +
    '5-6 m: tktpcvp\n' +
    '1-2 z: cdzkbqbhjn\n' +
    '3-4 h: hhhxh\n' +
    '4-15 g: gggfgggmggggggngpgp\n' +
    '1-6 z: zzswkz\n' +
    '1-5 g: gggggg\n' +
    '8-14 h: phjhfhxhjcztrw\n' +
    '9-11 h: hhhhhhhhhhlh\n' +
    '15-17 t: txcjtthtthtmtntttl\n' +
    '7-8 z: zzzpzdzj\n' +
    '2-9 x: xxxxxxxxlxxxtxlx\n' +
    '6-11 j: mjqtrjrmhbjpsjw\n' +
    '1-2 b: bbbbnbgbbbb\n' +
    '6-7 z: cptkzzz\n' +
    '12-13 v: vvwcwvvvvvqsdpvxvlvv\n' +
    '1-13 w: hwwwwwwwwwvwswwwwwwg\n' +
    '8-9 h: xjhgckphh\n' +
    '9-13 z: zzzzzzzzzzzzkzz\n' +
    '2-9 c: ncxccnclc\n' +
    '4-8 h: hnmhhfhhtmch\n' +
    '5-7 p: pppxkpst\n' +
    '2-4 b: fwlwgbbbxhbb\n' +
    '9-16 z: zzzzzzzzhzzzzzzvzz\n' +
    '5-18 t: ttttktttttttttttttt\n' +
    '1-2 t: hftttzt\n' +
    '16-19 w: jcpwnqwwwlmwfflwwgkw\n' +
    '1-3 d: dddg\n' +
    '13-16 r: hrlwdqrrtrrqrwrp\n' +
    '3-4 j: xjcj\n' +
    '18-19 n: nnnhnnnnnnnnnnnnnpnn\n' +
    '4-5 q: qqqqrq\n' +
    '13-14 d: ddddddddqdddptdd\n' +
    '8-13 n: vsnnnvwnrfqmnsctkq\n' +
    '2-12 d: ddddddddddddddddbv\n' +
    '7-9 m: msmmmmgmm\n' +
    '14-17 t: wttxttzrttccttttmt\n' +
    '1-3 z: hzbz\n' +
    '6-15 p: pppppzppppppppxpp\n' +
    '5-6 j: gggjxpdcnjjxjjnmv\n' +
    '4-6 k: kmwkkzf\n' +
    '2-10 j: pjjjzjjzsq\n' +
    '9-14 n: nnqnxnnnzwnnnnxmnnln\n' +
    '2-3 j: jjjmkffhsz\n' +
    '11-12 n: lxmlktcnknnn\n' +
    '17-18 w: wwwwwwpwwjkmwwcwwwww\n' +
    '4-6 k: vkkxfksbkkkkkkxkk\n' +
    '3-12 r: nrdrrkrcmbrkrsrrrr\n' +
    '7-8 t: ttttttwttt\n' +
    '4-6 s: scsssvkqsks\n' +
    '6-11 h: hhhhhwhhhhmfhhhh\n' +
    '4-9 n: nnnrnnnnnn\n' +
    '2-5 z: zzzwz\n' +
    '5-6 d: dddddxddd\n' +
    '6-7 f: ffffnrgx\n' +
    '4-13 d: xjndrdhnxdqnddj\n' +
    '5-6 v: cvktvf\n' +
    '2-15 x: lxhsltbnrdwwxbxftvb\n' +
    '9-16 r: rrrrrrrrrrrrrrrfrvrr\n' +
    '1-8 m: cwgsmxmrsmm\n' +
    '4-11 l: gdcllsllkllwcv\n' +
    '1-3 d: pfsjdhjjvzdsqkcq\n' +
    '10-16 r: rrrrrrrrrrrrrrrhrr\n' +
    '8-11 d: dmdddhddddkdddd\n' +
    '7-12 l: lldsllcllmlbl\n' +
    '8-14 b: wdztcvrbdcbmsjglr\n' +
    '2-6 w: wbwwwnw\n' +
    '6-7 g: tmlqggg\n' +
    '10-11 q: qqqqqqqzqdqqqnqqqqq\n' +
    '7-14 b: bbbvbbbbbbbbbbblbqbb\n' +
    '1-3 d: dgrdn\n' +
    '4-6 m: mmmmmsmm\n' +
    '5-6 v: vvvvvvv\n' +
    '1-2 s: fdsss\n' +
    '14-17 v: vvvvvwvvvvvvvwvvx\n' +
    '1-4 p: pppbpppppppg\n' +
    '6-7 j: jjjjjjj\n' +
    '10-12 h: hhhhhhhhhhhhhhhr\n' +
    '3-8 r: srhrrrprvzvpv\n' +
    '11-12 s: sssssssssstm\n' +
    '2-6 f: gffcnfrjhjjk\n' +
    '2-4 b: bbbqbb\n' +
    '9-11 l: llllllllrlclll\n' +
    '3-9 n: nnndvnnnnjn\n' +
    '4-18 j: jqbjlwhjmgfhzrszzjz\n' +
    '2-14 r: rrdkhrjrprrrwr\n' +
    '6-9 r: rrrrrrrrrrrr\n' +
    '3-7 h: hhghhgh\n' +
    '2-11 v: hzxmqjrknfvn\n' +
    '7-8 r: jwsrrrpgggjzqtcvprs\n' +
    '1-2 g: tnggg\n' +
    '4-10 z: mzpcsdnmzzmhmtl\n' +
    '4-10 j: jwvjdhtkfjjpq\n' +
    '12-13 w: wwwwwfwwmwwnwww\n' +
    '5-8 h: hhhdmhhphhhhhhhhhhh\n' +
    '9-10 j: jjjjjjjjjjxjjjj\n' +
    '6-8 t: ttgtttqgrvt\n' +
    '7-11 r: rrrrrrqrrrv\n' +
    '5-10 r: rrrrrrrrrrr\n' +
    '17-18 w: hwkgjwkwztwwxwwwww\n' +
    '6-10 s: bvrfsgjxfs\n' +
    '3-7 n: zclkprdknp\n' +
    '7-15 t: ttttfptttnwztttqvt\n' +
    '7-12 f: ffffszszfffn\n' +
    '6-11 x: mfxpwxbxxnqt\n' +
    '7-12 j: kjjjjjmhpvjjjj\n' +
    '2-3 d: ddsdb\n' +
    '3-5 c: czbcd\n' +
    '5-9 h: zbxhfglzk\n' +
    '6-7 x: xxxxxlxx\n' +
    '1-4 b: tbbt\n' +
    '8-12 p: pzlppppzxdvp\n' +
    '2-10 m: mfhhbrjzcmh\n' +
    '13-14 q: qqqqqqpqqqqqwvqqqx\n' +
    '4-5 l: hldll\n' +
    '15-16 n: snhnjgfbntnplcnf\n' +
    '6-10 x: xxxxhxxxxx\n' +
    '15-18 n: pnngsnxccmnkgznncfn\n' +
    '3-8 l: ghlllqmlgb\n' +
    '1-4 q: pqqwq\n' +
    '7-8 w: wwwwrwwdw\n' +
    '19-20 t: tttttttttttttttttttj\n' +
    '4-15 x: mfnfttdtqtdxkwp\n' +
    '3-8 z: zzzzzzzlz\n' +
    '12-16 d: dddqdddddddpdddsdd\n' +
    '8-11 h: hhhhhhhhhhhh\n' +
    '11-15 q: qqqqqqqqqqqpqqqqkq\n' +
    '8-11 f: fxqzkthfxnd\n' +
    '12-16 k: mbwkkkkkwgkkkklx\n' +
    '4-8 q: gbnbrhbqkbxpqn\n' +
    '3-13 c: cccccccccccctcc\n' +
    '3-4 m: mmjvwm\n' +
    '14-17 d: ddddzwxdqnrjdtddj\n' +
    '3-10 j: xjsjjjjjhhnjbjwj\n' +
    '11-13 s: sssssmssssnsl\n' +
    '5-8 f: kwnfrnvr\n' +
    '6-12 b: vfbjzbpkcbvdbb\n' +
    '6-7 q: gqqhhqq\n' +
    '1-4 q: qfkb\n' +
    '3-4 r: nrrc\n' +
    '11-14 z: znlzkbvzlzzvjz\n' +
    '5-7 h: hhkwvfb\n' +
    '3-7 t: trhfkdjm\n' +
    '10-11 n: nnnnnnnnnznn\n' +
    '2-3 q: qqjqjfbqnqtgxpfqn\n' +
    '3-5 f: ffffm\n' +
    '11-12 d: dtdddddcdddd\n' +
    '4-7 s: ssssvsss\n' +
    '2-14 f: qfkkkfkffznrcfk\n' +
    '7-13 z: dczxkclzzzztz\n' +
    '6-17 m: cjtfbndqvnnbmtmrm\n' +
    '10-11 w: wwwwwwwwwlww\n' +
    '7-18 d: vdppddfsfkddpjtfvr\n' +
    '17-18 p: ppppppppppppppppppp\n' +
    '12-13 c: zcchscccccqlc\n' +
    '5-6 r: pfjjrrzr\n' +
    '2-8 q: qqqqqqqzjq\n' +
    '5-6 b: blbbbps\n' +
    '4-5 l: lllllll\n' +
    '6-11 n: rgplnnsnnfn\n' +
    '4-10 j: rddsbjrstr\n' +
    '5-6 h: hvrltlrjhhnmqkxhhxkl\n' +
    '3-9 s: ssqsssssjssssssssbss\n' +
    '8-9 r: rvvrrrxsrrdtrb\n' +
    '11-13 b: tbtbwmbbbhqmb\n' +
    '8-9 b: fcbbpvlvjhmkf\n' +
    '15-16 f: ffffffffzffffffb\n' +
    '7-10 t: zfpwcwmxlbhxtjtp\n' +
    '2-5 z: zdzzbz\n' +
    '5-6 p: xphrnbf\n' +
    '6-11 f: qffpxfmfcpff\n' +
    '6-11 m: pmjrmjqjvrv\n' +
    '1-2 q: kwqqh\n' +
    '6-7 x: xxkxxxxkxxxx\n' +
    '12-15 w: wwwwwwwwwxwswwww\n' +
    '15-16 q: qqsfgdgqqqqqwqqqqq\n' +
    '9-18 q: qqqqqwqqqqqqqqqqqqqq\n' +
    '5-6 v: lvvqvv\n' +
    '14-16 b: dbfrbbbkbbpbkbbm\n' +
    '1-2 p: kjpp\n' +
    '2-4 q: krjv\n' +
    '2-7 t: mkmtdgh\n' +
    '1-2 s: jfss\n' +
    '8-12 v: vvvxhvvvxzmvqwvq\n' +
    '10-11 p: ptptjpcnppp\n' +
    '3-4 x: ffdhvxnxxx\n' +
    '3-8 x: xxfcxxxwxlxxxqxxx\n' +
    '1-2 g: gggg\n' +
    '6-8 d: dddddcdjjdlddddd\n' +
    '1-11 v: vvvvvnvvvvhvkvv\n' +
    '2-5 s: lfsnrs\n' +
    '4-17 t: ttthtttftttttttrt\n' +
    '12-14 z: rbfrzlfvwcbkczqm\n' +
    '13-15 m: kmmqhbmmmpmmhfm\n' +
    '4-8 v: vxnpvvhjvvj\n' +
    '6-8 s: lzzntswssxn\n' +
    '2-3 n: snngn\n' +
    '8-14 t: dttttttttttjttt\n' +
    '1-8 s: sssssssss\n' +
    '16-18 n: tznvpjjbgxmpfwhnbn\n' +
    '14-15 j: jjmjjfjjjjnjjjj\n' +
    '4-12 t: dkwtrtlqntpll\n' +
    '17-18 d: nrlrntddjdkddtdztm\n' +
    '4-7 q: xmmdqzqlfqmhf\n' +
    '16-17 n: nnnnnnnnfnnnnnnknnnn\n' +
    '9-11 m: mmmmmmmjjzs\n' +
    '2-6 b: dbjdgbglbgx\n' +
    '5-15 b: rrlbbkwbbntwfkb\n' +
    '4-5 n: pnjvn\n' +
    '1-4 b: pkbd\n' +
    '12-13 k: kkkkkkkkkkkdlkkkk\n' +
    '1-5 j: hbljlvdjnvfj\n' +
    '1-3 l: llll\n' +
    '8-10 j: jcmjqlbjjh\n' +
    '3-6 q: qqlhcnc\n' +
    '2-6 d: grqczd\n' +
    '1-2 b: blzbmnjfd\n' +
    '6-8 d: ddztdfdhdd\n' +
    '7-11 r: rrrtrdrxmsgrs\n' +
    '1-4 b: bbkc\n' +
    '2-5 s: ssmswssss\n' +
    '4-8 n: nnnbnnnxnn\n' +
    '2-3 d: dsrdddd\n' +
    '16-17 r: zrvrrrtzrrrrrrrrfr\n' +
    '4-9 v: jvmqvvvvvvwx\n' +
    '5-6 x: xxxxxb\n' +
    '5-6 t: tfttnc\n' +
    '3-4 p: pprfp\n' +
    '6-11 j: ptcjmstmtbhxfvpsww\n' +
    '4-5 x: xdhqx\n' +
    '6-7 d: dddddddd\n' +
    '4-5 b: wbjbppzbhjkf\n' +
    '2-6 g: gggggdg\n' +
    '3-8 j: jjjfrjjkjjjmjjml\n' +
    '7-11 h: hwhhbrhhhzh\n' +
    '5-9 b: lpgjbssbbxk\n' +
    '6-7 s: nsxssssssss\n' +
    '3-4 l: mllnl\n' +
    '5-6 r: rmpgdk\n' +
    '1-4 p: fpbmctbpl\n' +
    '5-6 s: scnmsss\n' +
    '2-4 m: jdkpmhmhmqtft\n' +
    '8-15 d: ddddpsdrdrqdmddd\n' +
    '6-7 s: snsssfs\n' +
    '4-6 g: ggggggg\n' +
    '7-8 x: xxxxbxxx\n' +
    '6-8 b: bmbbbvbhbbb\n' +
    '9-10 r: rrrrrpmrtmrrr\n' +
    '3-11 x: xxqpxtxmhdrxtxxxxxxx\n' +
    '10-12 l: lwlpljllllllll\n' +
    '3-5 l: lzlrl\n' +
    '3-5 b: bbbbvbpbbbbb\n' +
    '5-9 z: zwzzzzzzkc\n' +
    '12-14 l: qlnlxwrzpgllplbml\n' +
    '4-7 n: lwdzpjtmn\n' +
    '5-10 b: bbbbjbbbbx\n' +
    '6-7 j: njzdjjsxfpp\n' +
    '5-14 j: djnljhlrdmqnxcht\n' +
    '3-4 z: dtzz\n' +
    '10-11 m: tcmmhmhcsmm\n' +
    '9-13 p: pppphpppppcphfwbp\n' +
    '1-6 m: lmmmmw\n' +
    '2-4 q: hnzqqqprm\n' +
    '17-18 p: plpfzlkpzdhfpptgpq\n' +
    '3-17 r: rrprrrrrrrrrrrrrlrr\n' +
    '5-8 n: nnnznnnnnn\n' +
    '3-12 s: khjvspqsbmcst\n' +
    '6-8 w: cwbmhwqw\n' +
    '2-4 d: dddddp\n' +
    '1-6 b: tsbbbgbt\n' +
    '3-10 d: vvhzmpscssdwcxlvjjd\n' +
    '2-3 m: mmmmmmmmmnmmmmmmmmj\n' +
    '2-13 q: qqcpmtfwwffdqkwn\n' +
    '15-16 k: kkkkkkkkkkkkkkmf\n' +
    '2-3 j: jjnv\n' +
    '1-2 b: btbb\n' +
    '5-7 b: bbbbxhbbxtbb\n' +
    '5-7 g: gggggglgzg\n' +
    '3-4 b: bbpc\n' +
    '1-11 k: kkkkgkkkkkskk\n' +
    '1-14 h: lhthhhhnchhhhxhhhh\n' +
    '6-7 q: qfqlqbkqqqvqfqzqs\n' +
    '3-5 s: ssbsss\n' +
    '9-13 h: hhnhhjhvhdhhhbhhh\n' +
    '4-7 j: txdsljn\n' +
    '13-16 z: dgzkzzzkzzzzbxznw\n' +
    '7-8 s: sssssxgs\n' +
    '13-14 h: sphwccnrvhlbhjx\n' +
    '12-15 x: vtcxxxqjcwzbkxx\n' +
    '3-5 v: vjlvvvvvnv\n' +
    '11-14 k: klkkkkkkkkwkkkkkk\n' +
    '9-10 c: cccctcccccccccc\n' +
    '8-9 b: bbbbqlvnbq\n' +
    '3-7 d: ddddddddd\n' +
    '4-7 s: pbmwcmsrd\n' +
    '4-6 s: gxssqsw\n' +
    '7-16 r: rqdpsrrchrtcblnlsrr\n' +
    '10-15 x: gjbvwkmpzxfrvxx\n' +
    '3-6 k: drkchxtzkhnn\n' +
    '1-2 g: nzvkggbdg\n' +
    '16-17 f: fffffffffffffffkbf\n' +
    '1-9 t: gttttvttstt\n' +
    '10-12 c: cgcvcdcccwcccccj\n' +
    '7-8 k: zkkpkkkf\n' +
    '8-9 n: ngfnvnrwnnfl\n' +
    '11-13 j: hssxkhgvdhcjxhp\n' +
    '3-4 b: bbbbbbbbbbbbtck\n' +
    '3-7 b: nphsgbwbv\n' +
    '9-13 w: wwwwwwwwgwwwwwwwww\n' +
    '12-15 v: vvvvvvvvvvvvvvvvv\n' +
    '6-15 k: ftlgvkjxcngkwkjrnwn\n' +
    '11-13 k: kkskkkkkkkkkkkkk\n' +
    '1-13 s: sssslsnssssssssssss\n' +
    '9-11 t: ttttttttttttt\n' +
    '1-2 h: hmhh\n' +
    '6-7 h: hmhhghv\n' +
    '2-4 v: gvnv\n' +
    '3-6 l: hplmlltl\n' +
    '5-16 s: pqvnxbbxfnhdhmsswqx\n' +
    '4-13 z: dmwwlzznknzbzvzzw\n' +
    '9-10 c: cflcqdcwcvqmkjdqsgpc\n' +
    '4-10 f: mffxxfffflfsfgmlmxf\n' +
    '3-4 d: vdxdbw\n' +
    '1-3 z: wzdzzzg\n' +
    '9-10 z: zzzzwzzzlnz\n' +
    '2-5 n: knlfn\n' +
    '5-7 c: klcbczc\n' +
    '5-12 f: jrdqgrzkdplws\n' +
    '3-5 w: kftbw\n' +
    '1-4 s: sssgrs\n' +
    '6-9 n: hngnnnnjnnnn\n' +
    '13-14 k: kkkkkkkkkkqqkjk\n' +
    '10-18 s: xbsssxqqmvmshskjjs\n' +
    '5-6 k: snxjhwglkt\n' +
    '10-13 h: mtthhhxmsvlshhhnhl\n' +
    '7-16 z: zzzzzzwzzzzzzzzzzz\n' +
    '14-16 m: rmmvmhtmfmmmjmmcmmmm\n' +
    '8-11 s: sssssdsssspsss\n' +
    '6-9 g: clgdxllghzggqfvrxgzf\n' +
    '14-15 x: xxxxxxxxxxxsrxxxx\n' +
    '4-11 q: hqplnqwfsthmhspq\n' +
    '12-13 g: pzggkchrpjsct\n' +
    '7-12 t: zctsttbtttttt\n' +
    '3-4 s: jknhdlnsgssg\n' +
    '9-16 c: xlcrsqspctdcvhqc\n' +
    '4-19 f: vvzfktsstkbkngbfndmv\n' +
    '9-11 b: bbhbbbjmzbh\n' +
    '3-6 x: xqxxxvrx\n' +
    '7-8 g: gggggmgx\n' +
    '9-11 k: jrkpwggvkxk\n' +
    '3-4 m: mhpfmmmm\n' +
    '6-7 f: fqfffldrf\n' +
    '9-10 j: tjjcjdtjdj\n' +
    '2-5 c: qcccf\n' +
    '5-8 b: bbvbqbbtbbbbbb\n' +
    '6-7 q: hhpwdqqfxzgjgqv\n' +
    '2-5 q: rjqxs\n' +
    '9-11 q: hlcqqqxlrtq\n' +
    '2-13 n: nnnvwxgqbvdlnckgzgsr\n' +
    '15-16 l: jtcxfkljlwllpbgb\n' +
    '3-4 c: ccmscc\n' +
    '9-14 l: llllllllhllllhl\n' +
    '2-5 z: zzzgzzzw\n' +
    '2-8 b: blclwtdbz\n' +
    '2-3 l: llhllll\n' +
    '8-10 s: sssssssszr\n' +
    '1-4 f: fffz\n' +
    '4-11 t: ttttttttttltt\n' +
    '3-7 m: wcmkmznf\n' +
    '6-8 v: lnkgrvnvprjcjhfvwph\n' +
    '6-9 b: bkntwbwtbnk\n' +
    '3-4 j: jjjjj\n' +
    '2-12 z: qznmdxwggvnz\n' +
    '3-7 s: ssssslsssjssss\n' +
    '4-11 d: xdjddkjvqdddpddlmdmq\n' +
    '3-5 r: rrnrrrrdrr\n' +
    '6-8 g: zbgwtwzg\n' +
    '2-3 l: lmll\n' +
    '5-11 t: pvnmcqlcnztqf\n' +
    '5-6 j: jcljjdmmd\n' +
    '13-14 z: zzzzzzzzzzzzgr\n' +
    '4-6 q: xvcwqtd\n' +
    '6-9 t: tttttdttbtt\n' +
    '1-5 m: mmmmmmmmmmmbmmmmm\n' +
    '4-5 h: hnvvpgtgmh\n' +
    '3-7 t: ttpttttt\n' +
    '5-6 t: ngtttt\n' +
    '2-9 h: jxhhhhhhhhhhhlhwpgg\n' +
    '3-15 l: sslflhrrkcgvlhw\n' +
    '8-10 g: ggggwggbgdgg\n' +
    '8-14 t: tjttlttrhtgvtm\n' +
    '7-8 m: mmmmmfmm\n' +
    '10-11 n: kwnvzvnlnkn\n' +
    '7-11 f: fffffhjffffff\n' +
    '1-16 g: gggggggggggggggsggg\n' +
    '8-11 z: ntpzzdfzpzz\n' +
    '15-18 v: vwvnvvbvvkvvvvdjvjv\n' +
    '8-17 z: zzzzzzzgzzzzzzzznzz\n' +
    '7-8 j: jjfjjjjjjmrj\n' +
    '9-14 q: dprqqqzcfmcqqxqq\n' +
    '5-7 w: wwwwwwhw\n' +
    '10-11 g: gggggghggwmg\n' +
    '1-2 x: nhxx\n' +
    '9-10 t: tttktttlvttv\n' +
    '6-9 j: zpjhrjjffq\n' +
    '16-19 v: fvmrhxmvbvppzpwvvxbq\n' +
    '1-3 b: sbbbb\n' +
    '2-9 t: btbqhwgttpx\n' +
    '4-5 r: zdzrr\n' +
    '2-3 q: qqfq\n' +
    '8-9 j: vsjhjqvmjjx\n' +
    '5-14 l: llllwllllkllldllll\n' +
    '9-12 t: fltmrbqsjhqt\n' +
    '6-8 z: xdzzzlzzbj\n' +
    '3-20 f: zjrwrnzmlswpsrfjgjht\n' +
    '11-12 v: zjxrkvjkwqvf\n' +
    '11-15 r: rrrrrrrrrrtrrrjr\n' +
    '1-5 l: qlxlcllkllllwl\n' +
    '11-12 s: ssssssssssts\n' +
    '7-8 p: ppppppxw\n' +
    '7-9 b: bbbbhbnbfdbbbdb\n' +
    '4-8 f: grmvkbqbflnz\n' +
    '18-19 w: wgwwwwwwwwwwwwwwwdqw\n' +
    '6-14 r: rrrrrtrrrrrrrlrrrrv\n' +
    '1-2 t: tttttttgtztt\n' +
    '5-8 j: jxfjjjjjpfj\n' +
    '6-15 k: kfqnbvrjkmxptfdnnrkk\n' +
    '7-8 m: mmmmmmcqmmm\n' +
    '6-13 p: pppppppppppprpppppp\n' +
    '1-5 d: wdrpd\n' +
    '7-9 b: bbbbbbbbzbbbbb\n' +
    '3-11 j: jkrdcvmfctjvr\n' +
    '3-9 t: vpnqgxmjqccmjpkdt\n' +
    '3-7 l: llllllll\n' +
    '5-8 f: fffcnczfrfs\n' +
    '11-16 h: hhhshchnhxpshpdh\n' +
    '5-6 x: cxxtdx\n' +
    '11-15 k: gxltfbjcplqkkdhlc\n' +
    '3-9 g: twgvrlcgjljpwmrnxdtn\n' +
    '1-7 x: xxdxxxxxqqlxxxx\n' +
    '2-4 n: nnnt\n' +
    '11-13 h: hhhhhhhhhhlhhh\n' +
    '12-13 d: csddgmqzwmzmnj\n' +
    '11-12 h: hhbvhhhhchhx\n' +
    '7-11 h: hhhhhhhshhmhhh\n' +
    '15-16 w: wwwwwwwswwwwwwbh\n' +
    '3-4 f: sfffffffk\n' +
    '9-14 g: ggggggfggggggg\n' +
    '11-13 p: pppppppdppppppppppps\n' +
    '10-12 v: vhvvvvvvvgvnvvvfvv\n' +
    '1-19 l: lqlpllcdnllblkldlvp\n' +
    '2-3 t: rnbj\n' +
    '12-13 d: ddddsddddddbdqfdqld\n' +
    '2-15 l: klrxxlgjbvdqxgtgwpn\n' +
    '2-4 d: ddnp\n' +
    '7-8 d: dzdddjmtd\n' +
    '3-16 r: rrwrrrrrrrrrrrrrrr\n' +
    '11-12 d: rdddddddkddwrdx\n' +
    '6-8 z: zzzzgzlqzzvkz\n' +
    '15-18 g: gggggggggggggggggcgg\n' +
    '6-11 c: zcvcsxmclmrwk\n' +
    '5-11 h: hqszlhzshhjh\n' +
    '5-6 z: zjwzzz\n' +
    '8-12 q: qqqqqqqqqqqqqq\n' +
    '4-6 d: tdddtdrlx\n' +
    '2-5 s: zbfljqksqrnfrwrw\n' +
    '5-7 d: ddkddwzd\n' +
    '5-6 p: hpxpxp\n' +
    '7-9 g: ggggggxgw\n' +
    '3-5 b: tbfzb\n' +
    '9-14 z: pzszffgpzkkzczbznn\n' +
    '14-18 s: tsssslssslsrmzsvfzs\n' +
    '9-10 h: hhhhhhhhnhh\n' +
    '8-9 w: wnvwrxpwwzsmdzwmwl\n' +
    '1-2 d: qddddd\n' +
    '4-8 k: kkklkkkkkkk\n' +
    '3-4 m: kmzvvm\n' +
    '10-12 t: xntkttqkhgthrfhk\n' +
    '7-13 n: nnnnvrkznnnnn\n' +
    '1-4 l: lllklx\n' +
    '3-4 p: pnns\n' +
    '6-8 r: rrrrrdpr\n' +
    '5-10 v: vnztdmgllb\n' +
    '12-15 z: zzzzzzzzzzzgzzm\n' +
    '2-5 j: kjkkmjvcr\n' +
    '4-13 r: rrrrrrrrrrrrmzrr\n' +
    '3-6 w: wktbfw\n' +
    '6-8 h: hhhhhzhhhhh\n' +
    '5-16 m: dxlsprxpxflmmdls\n' +
    '3-4 v: xqvr\n' +
    '8-11 k: kkkkkkklkkkk\n' +
    '3-4 t: qtmsttdttmzthtttt\n' +
    '4-6 w: wkwbkww\n' +
    '1-2 d: dddc\n' +
    '9-10 b: bbbbbbbbbb\n' +
    '11-12 n: nnnnnnnnnnnnhn\n' +
    '9-10 m: nmhjhtmvvm\n' +
    '2-5 l: hgllrllllllll\n' +
    '3-4 t: tvtkt\n' +
    '5-6 p: bpbmppwpqnpxp\n' +
    '4-8 r: rrrnrrrrrrm\n' +
    '6-12 z: zhzbzszkzwbgvz\n' +
    '13-14 b: bjbbbcbqdbbbjwbbbbbb\n' +
    '4-8 n: nnnnnnnnn\n' +
    '6-10 l: lllllllllll\n' +
    '4-6 q: qqqqqqq\n' +
    '3-5 d: bddzv\n' +
    '9-10 l: vllwpvltmwvl\n' +
    '7-14 p: cppbprpppppphm\n' +
    '12-17 k: kkkkkkkkkkkkkkkkkkk\n' +
    '6-7 t: wstglttttltwqpxd\n' +
    '2-5 t: wtrkt\n' +
    '10-18 v: vvvvvvvvrgkbvvsvvvv\n' +
    '8-9 p: nvsqptgpphmh\n' +
    '5-7 c: jccvlccsmqbrfnspf\n' +
    '4-6 g: zsggtg\n' +
    '6-8 p: pppphpqdppdp\n' +
    '2-14 f: kqfffffgfffffdffff\n' +
    '7-9 h: whhhhhhhh\n' +
    '2-3 w: wmlwwwwwwwwwwwwwwwzw\n' +
    '5-6 h: hhhhghhhhhx\n' +
    '1-5 z: dzzzzzzz\n' +
    '14-16 g: ggggggggggggglghl\n' +
    '4-8 c: ccfcmcccccf\n' +
    '2-3 h: hwhd\n' +
    '9-12 w: wwwczwwwzwwwwwwww\n' +
    '2-3 b: bpqb\n' +
    '2-7 b: dbrxzktblnqgj\n' +
    '2-8 w: wgwwwwwbtw\n' +
    '6-11 b: bbbbbbbbbbbb\n' +
    '7-12 m: ztmpmzvmtmbc\n' +
    '4-5 f: kxhkg\n' +
    '12-13 n: xlnqqnbdqnfvnldjf\n' +
    '3-4 r: jzrr\n' +
    '9-12 q: qqqqwqqqsqvbqcs\n' +
    '11-12 c: txkdrczkwcccbjfwctcg\n' +
    '9-11 w: xwwwwwjdrwgwgrw\n' +
    '4-12 n: qfnpgktmggzmr\n' +
    '2-11 t: ttflcgqrrmx\n' +
    '8-15 d: rdjkddzdddpttdbg\n' +
    '9-12 d: ddddddddbdddvd\n' +
    '5-10 h: lhvlhhctdhdq\n' +
    '10-16 b: nbbbbbbbbsmcmbbr\n' +
    '5-10 d: qmddddddddd\n' +
    '4-6 h: hhhhthh\n' +
    '2-5 j: jjksjmmsvttvfsgf\n' +
    '7-9 c: xbhznccvk\n' +
    '9-13 m: pshmvvqqmnkkmklrhxq\n' +
    '8-9 s: ssssssssssss\n' +
    '13-17 p: wpnmpwjbntllpqmhp\n' +
    '6-7 d: ddddddkddddd\n' +
    '6-7 p: gvpspmj\n' +
    '3-15 s: gwsllhxsrfzqlmsls\n' +
    '5-7 v: vvvvvvwvv\n' +
    '4-5 x: mvxjx\n' +
    '2-5 q: bpkjqqqttgpddg\n' +
    '4-6 d: dddhdhd\n' +
    '4-6 s: scsncs\n' +
    '5-10 m: mmmmpmmmmkmmmm\n' +
    '5-14 r: rrrrrrrrrrrrrsrrrr\n' +
    '7-10 d: zddddddldxtmfzddd\n' +
    '2-5 x: vxwxz\n' +
    '2-5 h: khxnhmczfhrwdkggd\n' +
    '12-16 v: vvvrvfvvvkvvvvvxkvc\n' +
    '3-4 f: rcbf\n' +
    '11-15 m: mklrxvmkmmvmmzmm\n' +
    '9-14 w: qwwwwwlwbwwwwswww\n' +
    '7-16 z: zzzzzzbzzzzzzzzpzzzz\n' +
    '16-18 f: fffffffqffffffffff\n' +
    '1-5 l: llllll\n' +
    '3-4 m: vmmmpcd\n' +
    '15-18 j: jjjjjjjjjjjjjjmjjjj\n' +
    '3-4 g: ggdgg\n' +
    '12-14 x: xrmzlxxlrxfglxj\n' +
    '3-4 f: tfxrbbffqf\n' +
    '7-8 p: pppppbvpc\n' +
    '12-13 t: tttttfzwtttvt\n' +
    '7-8 n: nnnnnnns\n' +
    '10-12 d: dwjdddddwdkqdm\n' +
    '4-6 f: fzwrzjrcq\n' +
    '6-8 b: tbbbbbcbbbbb\n' +
    '4-7 v: vvvgvvvv\n' +
    '18-19 k: kkkkkkkkkkkkkkkkkkm\n' +
    '7-10 l: llllllcllll\n' +
    '1-6 d: bdddddddd\n' +
    '8-14 r: rrrrwrxrrrrrrgrrdrz\n' +
    '2-10 n: nfnnnnlnnnnn\n' +
    '5-6 l: lklllhl\n' +
    '17-19 r: rrrrrrrrrrrrrrrrrrj\n' +
    '4-7 p: tknpspbhpcr\n' +
    '5-7 x: tvhrbsrtf\n' +
    '10-11 x: xxxxxxxxxxxx\n' +
    '13-15 v: vsbvvbvlvqcznwvvvh\n' +
    '4-5 v: vpsdlnvvbvvvpfqvvvv\n' +
    '16-18 k: lrhszjpkxkqpzskzbkvt\n' +
    '12-13 c: ccccccccccccdc\n' +
    '9-14 p: ppvppppppppppppppppp\n' +
    '5-11 b: pjbbbbbbbbblbvb\n' +
    '2-4 m: fmtwnjwlfcsgpdmxhtd\n' +
    '7-12 l: zflcvdlllfkvtfqptll\n' +
    '11-12 g: ggggggnjghggkggfn\n' +
    '8-10 z: dfzxgzzbpz\n' +
    '5-6 w: wwwfkc\n' +
    '9-10 w: wwwwwwbwwhww\n' +
    '5-6 g: kgggjg\n' +
    '4-8 s: ssssssscs\n' +
    '12-20 t: ttttttltttvttttttttt';

module.exports = {testData};
